name: build
on: 
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      name: build modpack
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
        
        - name: compile and upload
          uses: actions/upload-artifact@v4
          with:
            name: create-elevator-linker
            path: |
              data/
              pack.mcmeta
            if-no-files-found: error
