on: [push]

jobs:
    build-and-publish:
      runs-on: ubuntu-latest
      name: My workflow
      steps:
        - name: Execute Action Graph
          uses: actionforge/action@346e5bce9c84f281653913c47709ad64d1772f66 # v0.9.62
          with:
            graph_file: build.yml